matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.list_matkul, name='list_matkul'),
    path('create-course', views.create_matkul, name='create_matkul'),
    path('update-course/<slug:slug>', views.update_matkul, name='update_matkul'),
    path('delete-course/<slug:slug>', views.delete_matkul, name='delete_matkul'),
    path('course-details/<slug:slug>', views.matkul_desc, name='matkul_desc')

]

webtimi/urls.py
from django.contrib import admin
from django.urls import path, include
from booksearch import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('story1/', include('story1.urls')),
    path('courses/', include('matkul.urls')),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('book-search/', include('booksearch.urls')),
    path('book-data/', views.book_data, name='book_data'),
]

matkul/models.py
from django.db import models

# Create your models here.

class Matkul(models.Model):
    nama = models.CharField(max_length=100, unique=True)
    singkatan = models.SlugField(unique=True)
    dosen = models.CharField(max_length=100, null=True)
    sks = models.IntegerField()
    desc = models.TextField(null=True, blank=True)
    semester = models.CharField(max_length=20, null=True)
    kelas = models.CharField(max_length=1, null=True)
    
    def __str__(self):
        return self.nama

matkul/forms.py
from django import forms
from django.forms import ModelForm
from .models import Matkul

class MatkulForm(ModelForm):
    class Meta:
        model = Matkul      # Decide the model
        fields = '__all__'  # create form with all the attr. contained in class Matkul (Models.py)

        widgets = {
            'nama': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Course name'}),
            'singkatan': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Course code/abbreviation'}),
            'dosen': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Lecturer of the course'}),
            'sks': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'SKS/course credit'}),
            'desc': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'A brief description of the course'}),
            'semester': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Course semester'}),
            'kelas': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your classroom'}),
        } 

matkul/views.py
from django.shortcuts import render, redirect
from .models import Matkul
from .forms import MatkulForm
# Create your views here.

def list_matkul(request):
    list_matkul = Matkul.objects.all()
    return render(request,'matkul/matkul.html', {'list_matkul':list_matkul})


def matkul_desc(request, slug):
    matkul = Matkul.objects.get(singkatan=slug)

    if not matkul.desc:
        context = {'matkul':matkul}
        return render(request, 'matkul/matkul_warning.html', context)
    
    context = {'matkul':matkul}
    return render(request, 'matkul/matkul_content.html', context)


def create_matkul(request):
    form = MatkulForm()

    if request.method == "POST":
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/courses")

    context = {'form':form}
    return render(request, 'matkul/matkul_form.html', context)


def update_matkul(request, slug):
    matkul = Matkul.objects.get(singkatan=slug)
    form = MatkulForm(instance=matkul)

    if request.method == "POST":
        form = MatkulForm(request.POST, instance=matkul)
        if form.is_valid():
            form.save()
            return redirect("/courses")

    context = {'form':form}
    return render(request, 'matkul/matkul_form.html', context)


def delete_matkul(request, slug):
    matkul = Matkul.objects.get(singkatan=slug)

    if request.method == "POST":
        matkul.delete()
        return redirect("/courses")

    context = {'matkul':matkul}
    return render(request, 'matkul/matkul.html', context)

matkul/templates/matkul/matkul.html
{% extends 'mainpage/base.html' %}
{% block title %}
Courses
{% endblock %}

{% block content %}
{% include 'mainpage/header.html' %}

<div class="container-xl">
    <h1>Courses</h1>
    <div class="row">
        {% for matkul in list_matkul %}
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">{{matkul.nama}} (Kelas {{matkul.kelas}})</h1>
                    <h2 class="card-subtitle mb-1 text-muted">{{matkul.dosen}}</h2>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Jumlah SKS: {{matkul.sks}}</li>
                    <li class="list-group-item">Semester: {{matkul.semester}}</li>
                </ul>
                <a href="{% url 'matkul:matkul_desc' matkul.singkatan %}" class="btn btn-outline-dark">Details</a>
                <a href="{% url 'matkul:update_matkul' matkul.singkatan %}" class="btn btn-outline-dark">Update</a>
                <form action="{% url 'matkul:delete_matkul' matkul.singkatan %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-outline-dark btn-block but-del" type="submit" value="Delete">
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="add-btn">
        <a class="btn btn-dark btn-lg but-add" href="{% url 'matkul:create_matkul' %}" role="button">Add Course</a>
    </div>
    
</div>
{% endblock %}

matkul/templates/matkul/matkul_content.html
{% extends 'mainpage/base.html' %}
{% block title %}
{{matkul.nama}}
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl short">
    <div class="body-short">
        <h1>{{matkul.nama}}</h1>
        <h2 class="sub-heading">Lecturer: {{matkul.dosen}}</h2>
        <h2 class="sub-heading">Semester: {{matkul.semester}}</h2>
        <h2 class="sub-heading">Class: {{matkul.singkatan}}-{{matkul.kelas}}</h2>
        <p class="long-par">{{matkul.desc}}</p>
        <a class="btn btn-dark btn-lg but-back" href="{% url 'matkul:list_matkul' %}" role="button">Go Back</a>
    </div>
</div>

{% endblock %}

matkul/templates/matkul/matkul_form.html
{% extends 'mainpage/base.html' %}
{% block title %}
Create Course
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    {% if request.get_full_path == "/courses/create-course" %}
    <h1>Add Course</h1>
    {% else %}
    <h1>Update Course</h1>
    {% endif %}
    <div class="form-group">
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            {% if request.get_full_path == "/courses/create-course" %}
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Create">
            {% else %}
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Update">
            {% endif %}
        </form>
    </div>
    <a class="btn btn-dark btn-lg but-back" href="{% url 'matkul:list_matkul' %}" role="button">Go Back</a>
</div>
{% endblock %}

matkul/templates/matkul/matkul_warning.html
{% extends 'mainpage/base.html' %}
{% block title %}
Oops..
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl short">
    <div class="body-short">
        <h1>Sorry..</h1>
        <p class="long-par">We couldn't show the details of "{{matkul.nama}}" because there is no description about it. Please make sure you have added or updated the course.</p>
        <a class="btn btn-dark btn-lg but-back" href="{% url 'matkul:list_matkul' %}" role="button">Go Back</a>
    </div>
</div>

{% endblock %}