activities/urls.py
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('', views.list_activities, name='list_activities'),
    path('create-activity', views.create_activity, name='create_activity'),
    path('edit-activity/<str:name>', views.edit_activity, name='edit_activity'),
    path('delete-activity/<str:name>', views.delete_activity, name='delete_activity'),
    path('<int:activity_id>/add-participant', views.add_participants, name='add_participant'),
    path('details', views.details, name='details')
]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.list_matkul, name='list_matkul'),
    path('create-course', views.create_matkul, name='create_matkul'),
    path('update-course/<slug:slug>', views.update_matkul, name='update_matkul'),
    path('delete-course/<slug:slug>', views.delete_matkul, name='delete_matkul'),
    path('course-details/<slug:slug>', views.matkul_desc, name='matkul_desc')

]

webtimi/urls.py
from django.contrib import admin
from django.urls import path, include
from booksearch import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('story1/', include('story1.urls')),
    path('courses/', include('matkul.urls')),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('book-search/', include('booksearch.urls')),
    path('book-data/', views.book_data, name='book_data'),
]

activities/models.py
from django.db import models

# Create your models here.
class Participant(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Activity(models.Model):

    class ActivityCategory(models.TextChoices):
        general = "General"
        informative = "Informative"
        fun = "Fun"
        important = "Important"
        others = "Others"

    name = models.CharField(max_length=100, unique=True)
    category = models.CharField(
        max_length=20,
        choices=ActivityCategory.choices,
        default=ActivityCategory.general,
        )
    desc = models.CharField(max_length=200, blank=True, null=True)
    participants = models.ManyToManyField(Participant, blank=True)

    def __str__(self):
        return self.name

activities/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class ActivityForm(ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Activity name'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'A brief description of the activity'}),
            'participants': forms.TextInput(attrs={'class': 'form-control'}),
        } 

class ParticipantForm(ModelForm):
    class Meta:
        model = Participant
        fields = '__all__'

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Participant name'}),
            
        } 

activities/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
# Create your views here.

def list_activities(request):
    list_activities = Activity.objects.all()
    return render(request, 'activities/list_activities.html', {'list_activities': list_activities})

def create_activity(request):
    form = ActivityForm()

    if request.method == "POST":
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/activities')

    context = {'form_activ':form}
    return render(request, 'activities/activities_form.html', context)

def edit_activity(request, name):
    activity = Activity.objects.get(name=name)
    form = ActivityForm(instance=activity)

    if request.method == "POST":
        form = ActivityForm(request.POST, instance=activity)
        if form.is_valid():
            form.save()
            return redirect('/activities')

    context = {'form_activ':form}
    return render(request, 'activities/activities_form.html', context)


def delete_activity(request, name):
    activity = Activity.objects.get(name=name)

    if request.method == "POST":
        activity.delete()
        return redirect("/activities")

    context = {'activity':activity}
    return render(request, 'activities/list_activities.html', context)

def add_participants(request, activity_id):
    activity = Activity.objects.get(id=activity_id)
    form = ParticipantForm()

    if request.method == "POST":
        form = ParticipantForm(request.POST)    # hasil inputan (request.POST) ParticipantForm dimasukan ke 'form'
        if form.is_valid():
            form.save() # hasil inputan disimpan
            person = form.cleaned_data  # diambil data hasil inputan dengan: .cleaned_data, kemudian assign ke 'person'
            participant = form.cleaned_data['name'] # dari datanya, diambil data yang attribute 'name'
            activity.participants.create(name=participant)  # kemudian di create (add) participant untuk aktvitas yang terkait
            activity.save() # di save trus kelar deh :)))
            return redirect('/activities')
    
    context = {'form_participant':form}
    return render(request, 'activities/add_participant.html', context)

def details(request):
    list_activities = Activity.objects.all()
    return render(request, 'activities/details.html', {'list_activities': list_activities})

activities/templates/activities/activities_form.html
{% extends 'mainpage/base.html' %}
{% block title %}
{% if request.get_full_path == "/activities/create-activity" %}
Create Activity
{% else %}
Update Activity
{% endif %}
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    {% if request.get_full_path == "/activities/create-activity" %}
    <h1>Create Activity</h1>
    {% else %}
    <h1>Edit Activity</h1>
    {% endif %}
    <div class="form-group">
        <form action="" method="post">
            {% csrf_token %}
            {{form_activ.name.label_tag}}
            {{form_activ.name}}
            {{form_activ.category.label_tag}}
            {{form_activ.category}}
            {{form_activ.desc.label_tag}}
            {{form_activ.desc}}
            {% if request.get_full_path == "/activities/create-activity" %}
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Create">
            {% else %}
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Update">
            {% endif %}
        </form>
    </div>
    <a class="btn btn-dark btn-lg but-back" href="{% url 'activities:list_activities' %}" role="button">Go Back</a>
</div>


{% endblock %}

activities/templates/activities/add_participant.html
{% extends 'mainpage/base.html' %}
{% block title %}
Add Participant
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>Add Participant</h1>
   

    <div class="form-group">
        <form action="" method="post">
            {% csrf_token %}
            {{form_participant.name.label_tag}}
            {{form_participant.name}}
            
            <input class="btn btn-dark btn-lg but-add" type="submit" value="Add">
            
        </form>
    </div>
    <a class="btn btn-dark btn-lg but-back" href="{% url 'activities:list_activities' %}" role="button">Go Back</a>
</div>


{% endblock %}

activities/templates/activities/details.html
{% extends 'mainpage/base.html' %}
{% block title %}
Details
{% endblock %}


{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>Details</h1>
    
  <div class="table-responsive-xl">
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Activity</th>
            <th scope="col">Category</th>
            <th scope="col">Description</th>
            <th scope="col">Participants</th>
          </tr>
        </thead>
        <tbody>
          {% for act in list_activities %}
          <tr>
            <th scope="row">{{act.name}}</th>
            <td>{{act.category}}</td>
            <td>{{act.desc}}</td>
            <td>
                {% for part in act.participants.all %}
                <p>{{part.name}}</p>
                {% endfor %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
    
  <a class="btn btn-dark btn-lg but-back" href="{% url 'activities:list_activities' %}" role="button">Go Back</a>
</div>


{% endblock %}

activities/templates/activities/list_activities.html
{% extends 'mainpage/base.html' %}
{% block title %}
Activities
{% endblock %}

{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>Activities</h1>
    {% if not list_activities %}
    <p class="long-par">There are no activities yet. Create one now!</p>
    <div class="add-btn">
        <a class="btn btn-dark btn-lg but-add" href="{% url 'activities:create_activity' %}" role="button">Create Activity</a>
    </div>
    {% else %}
    <div class="row">
        {% for act in list_activities %}
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">{{act.name}}</h1>
                    <h2 class="card-subtitle mb-1 text-muted">Category: {{act.category}}</h2>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{act.desc}}</li>
                </ul>
                <a href="{% url 'activities:edit_activity' act.name %}" class="btn btn-outline-dark">Edit</a>
                <a href="{% url 'activities:add_participant' act.id %}" class="btn btn-outline-dark">Add Participant</a>
                <form action="{% url 'activities:delete_activity' act.name %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-outline-dark btn-block but-del" type="submit" value="Delete">
                </form>

                
            </div>
        </div>
        {% endfor %}
    </div>
    
    <div class="add-btn special">
        <a class="btn btn-dark btn-lg but-add" href="{% url 'activities:create_activity' %}" role="button">Add Activity</a>
        <a class="btn btn-dark btn-lg but-add" href="{% url 'activities:details' %}" role="button">Details</a>
    </div>
    {% endif %}
    
</div>


{% endblock %}