activities/urls.py
from django.urls import path

from . import views

app_name = 'activities'

urlpatterns = [
    path('', views.list_activities, name='list_activities'),
    path('create-activity', views.create_activity, name='create_activity'),
    path('edit-activity/<str:name>', views.edit_activity, name='edit_activity'),
    path('delete-activity/<str:name>', views.delete_activity, name='delete_activity'),
    path('<int:activity_id>/add-participant', views.add_participants, name='add_participant'),
    path('details', views.details, name='details')
]

booksearch/urls.py
from django.urls import path

from . import views

app_name = 'booksearch'

urlpatterns = [
    path('', views.index, name='index'),
]

mainpage/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('gallery', views.gallery, name='gallery'),
    path('coming-soon', views.comingsoon, name='coming-soon'),
]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.list_matkul, name='list_matkul'),
    path('create-course', views.create_matkul, name='create_matkul'),
    path('update-course/<slug:slug>', views.update_matkul, name='update_matkul'),
    path('delete-course/<slug:slug>', views.delete_matkul, name='delete_matkul'),
    path('course-details/<slug:slug>', views.matkul_desc, name='matkul_desc')

]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

webtimi/urls.py
from django.contrib import admin
from django.urls import path, include
from booksearch import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('story1/', include('story1.urls')),
    path('courses/', include('matkul.urls')),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('book-search/', include('booksearch.urls')),
    path('book-data/', views.book_data, name='book_data'),
]

mainpage/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'mainpage/index.html')

def gallery(request):
    return render(request, 'mainpage/gallery.html')

def about(request):
    return render(request, 'mainpage/about.html')

def comingsoon(request):
    return render(request, 'mainpage/other.html')

mainpage/templates/mainpage/about.html
{% extends 'mainpage/base.html' %}

{% load static %}

{% block title %}
About Me
{% endblock %}



{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>About Me</h1>
    <div class="bio">
        <img src="{% static 'mainpage/img/IMG_20200707_140113-1.jpg' %}" alt="">
        <div class="text">
            <h1>Timothy Efraim Hotasi</h1>
            <p class="sub-heading">Computer Science Student</p>
            <p class="sub-heading"> University of Indonesia</p>
            <p class="long-par">Born in Jakarta, Indonesia. Currently 19 years old. Determined person. Novice programmer. Passionate designer. Simple photographer. Average pianist. Cat lover. Love spending time playing games and gazing at the sky.</p>

        </div>
        
    </div>
</div>

<div class="container-xl">
    <h1>Education</h1>
    <div class="card-deck">
        <div class="card">
          <img src="{% static 'mainpage/img/image-2.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">SMA Regina Pacis Bogor</p>
            <p class="year">(2016 - 2019)</p>

          </div>

        </div>
        <div class="card">
          <img src="{% static 'mainpage/img/image-1.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">University of Indonesia</p>
            <p class="year">(2019 - )</p>
            
          </div>

        </div>
        <div class="card">
          <img src="{% static 'mainpage/img/image-3.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <p class="card-text">SMP Regina Pacis Bogor</p>
            <p class="year">(2013 - 2016)</p>

          </div>
        </div>
      </div>
</div>

<div class="container-xl">
    <h1>Experience</h1>
    
    <div class="exp">
        <img src="{% static 'mainpage/img/Logotype [800px].svg' %}">
        <div class="exp-content">
            <h1>Compfest</h1>
            <p class="sub-heading">Visual Design (Staff)</p>    
            <p class="long-par">Compfest is the biggest and leading one stop IT Event held by students in University of Indonesia. I spent my time there designing publication things like announcements, posters, and so on. Working as a visual designer team motivates me to design even more.</p>
        </div>
    </div>

    <div class="exp">
        <img src="{% static 'mainpage/img/image 4.svg' %}">
        <div class="exp-content">
            <h1>Sekolah BEM Fasilkom</h1>
            <p class="sub-heading">Pengembangan Teknologi Informasi</p>    
            <p class="long-par">Sekolah BEM Fasilkom or SBF is a program that is dedicated to freshmen to participate in Faculty-enviroment organization. I was taking a part in Pengembangan Teknologi Informasi (PTI) which taught me about 
                on-campus technology engagement. Besides that, PTI also taught me about Web Development. I got to know HTML, CSS, Javascript, and Django. It motivates me to become a web developer.</p>
        </div>
    </div>
    
</div>

<div class="container-xl">
    <h1>Skills</h1>
    <div class="list-skill">

    
    <div class="card" style="width: 30rem;">
        <div class="card-body">
          <p class="sub-heading">Soft Skill</p>
          <p>Hardworker</p>
          <p>Easy to work in group</p>
          <p>Creative</p>
          <p>Open-minded</p>
          
        </div>
      </div>

    <div class="card" style="width: 30rem;">
        <div class="card-body">
          <p class="sub-heading">Hard Skill</p>
          <p>Design (Photoshop, Figma)</p>
          <p>Programming (Java)</p>
          <p>Photograhy</p>
          
        </div>
      </div>

    </div>
    
</div>

{% include 'mainpage/footer.html' %}
{% endblock %}

mainpage/templates/mainpage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!--CSS link-->
    <link rel="stylesheet" href="{% static 'mainpage/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
    
</body>
</html>

mainpage/templates/mainpage/footer.html
{% load static %}

<footer>
    <div class="contacts">
        <img src="{% static 'mainpage/img/Logo.svg' %}" alt="logo-timmy">
        
        <div class="contacts-info">
            <h2>Contacts</h2>
            <div class="cont-logo">
                <a href="https://www.instagram.com/timothyefraimlg/"><img src="{% static 'mainpage/img/instagram.svg' %}" alt="/"></a>
                <a href="https://timeline.line.me/user/_ddsVorZ8EgF-HT5mYGTgSKG_xbZrnL1_S9XRf7s"><img src="{% static 'mainpage/img/line.svg' %}" alt="/"></a>
                <a href="https://wa.me/087873257805"><img src="{% static 'mainpage/img/whatsapp.svg' %}" alt="/"></a>
            </div> 
        </div>
             
    </div>
    <p>@timmyworks</p>
</footer>

mainpage/templates/mainpage/gallery.html
{% extends 'mainpage/base.html' %}

{% load static %}

{% block title %}
Gallery
{% endblock %}



{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>Gallery</h1>
    
    <div class="row row-cols-1 row-cols-md-3">
        <div class="col mb-4">
          <div class="card">
            <img src="{% static 'mainpage/img/1.jpg' %}" class="card-img-top" alt="...">
            
          </div>
        </div>
        <div class="col mb-4">
          <div class="card">
            <img src="{% static 'mainpage/img/2.jpg' %}" class="card-img-top" alt="...">
            
          </div>
        </div>
        <div class="col mb-4">
          <div class="card">
            <img src="{% static 'mainpage/img/3.jpg' %}" class="card-img-top" alt="...">
            
          </div>
        </div>
        <div class="col mb-4">
          <div class="card">
            <img src="{% static 'mainpage/img/4.jpg' %}" class="card-img-top" alt="...">
            
          </div>
        </div>
        <div class="col mb-4">
            <div class="card">
              <img src="{% static 'mainpage/img/5.jpg' %}" class="card-img-top" alt="...">

            </div>
          
        </div>
        <div class="col mb-4">
          <div class="card">
            <img src="{% static 'mainpage/img/6.jpg' %}" class="card-img-top" alt="...">

          </div>
        
      </div>   
    </div>

    <p>Pictures taken by me.</p>
    <p>More to come.</p>

</div>

{% include 'mainpage/footer.html' %}
{% endblock %}

mainpage/templates/mainpage/header.html
{% load static %}

<nav class="navbar navbar-expand-sm fixed-top navbar-dark fix-nav">
    <div class="container-fluid">
      <img src="{% static 'mainpage/img/T.svg' %}" width="40" height="100" alt="" loading="lazy">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse align-items-center" id="navbarResponsive">
        
        <ul class="navbar-nav ml-auto align-items-center">
        {% with url_name=request.resolver_match.url_name %}
            <li class="nav-item"> 
            <a class="nav-link {% if url_name == 'home' %}active{% endif %}" href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link {% if url_name == 'about' %}active{% endif %}" href="{% url 'home:about' %}">About Me</a>
            </li>

            <li class="nav-item">
            <a class="nav-link {% if url_name == 'gallery' %}active{% endif %}" href="{% url 'home:gallery' %}">Gallery</a>
            </li>

            <li class="nav-item dropdown">
            <a class="nav-link {% if url_name != 'home' and url_name != 'about' and url_name != 'gallery' %}active{% endif %} dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Others
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'story1:story1' %}">Story 1</a>
                <a class="dropdown-item" href="{% url 'home:coming-soon' %}">Coming<br>Soon</a>
                <a class="dropdown-item" href="{% url 'matkul:list_matkul' %}">Course</a>
                <a class="dropdown-item" href="{% url 'activities:list_activities' %}">Activity</a>
                <a class="dropdown-item" href="{% url 'booksearch:index' %}">Books</a>
            </div>
            </li>
        {% endwith %}
        </ul>
      </div>
    </div>
</nav>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

mainpage/templates/mainpage/index.html
{% extends 'mainpage/base.html' %}

{% load static %}

{% block title %}
Home
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'mainpage/script.js' %}"></script>
{% endblock %}


{% block content %}
<div class="container-fl">
    <div class="logo-timmyworks">
        <img src="{% static 'mainpage/img/Logo Panjang.svg' %}" alt="/">
        <div class="user-auth">
            {% if user.is_authenticated %}
                <p>Hello, {{user.username}}!</p>
                <a href="/accounts/logout/">Log Out?</a>
            {% else %}
                <a href="/accounts/login/">Login</a>
                <a href="/accounts/signup/">Sign Up</a>
            {% endif %}
        </div>       
    </div>

    <div class="mini-bio">
        <img src="{% static 'mainpage/img/4284-1.jpg' %}" alt="profile-picture">
        <h1>Timothy Efraim</h1>
        <p>Currently a Computer Science student.</p>
        <p>Welcome aboard!</p>
    </div>
    
    <nav class="mini-nav">
        <ul>
            <li><a href="{% url 'home:gallery' %}">gallery</a></li>
            <li><a href="{% url 'home:about' %}">about me</a></li>
        </ul>
    </nav>
</div>

<div class="container-lg toolazy">
    <h1 class="tldr">TLDR</h1>
    <div class="main-accordion">
        <div class="d-flex flex-column mb-3">

            <div class="accordion">
                <div class="d-flex justify-content-between accordion-head">
                    <h2 class="sub-heading accordion-title">Bio.</h2>
                    <div class="d-flex align-items-center updown-btn">
                        <input class="up-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Up">
                        <input class="down-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Down">
                    </div>              
                </div>

                <div class="accordion-content">
                    <p>> You can call me Timothy/Timmy/Mothy.<br>> I'm 19 years old, lives in Bogor. My interest are coding, design, photographs, and cats.</p>
                </div>
            </div>


            <div class="accordion">
                <div class="d-flex justify-content-between accordion-head">
                    <h2 class="sub-heading accordion-title">Education.</h2>
                    <div class="d-flex align-items-center updown-btn">
                        <input class="up-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Up">
                        <input class="down-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Down">  
                    </div>              
                </div>

                <div class="accordion-content">
                    <p>> Majoring in Computer Science at University of Indonesia.<br>> Before that, I was a Regina Pacis Senior and Junior High School student.</p>
                </div>
            </div>

            <div class="accordion">
                <div class="d-flex justify-content-between accordion-head">
                    <h2 class="sub-heading accordion-title">Experience.</h2>
                    <div class="d-flex align-items-center updown-btn">
                        <input class="up-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Up">
                        <input class="down-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Down">  
                    </div>              
                </div>

                <div class="accordion-content">
                    <p>> Compfest - Staff of Visual Design<br>> Sekolah BEM Fasilkom - Pengembangan Teknologi Informasi</p>
                </div>
            </div>

            <div class="accordion">
                <div class="d-flex justify-content-between accordion-head">
                    <h2 class="sub-heading accordion-title">Skills.</h2>
                    <div class="d-flex align-items-center updown-btn">
                        <input class="up-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Up">
                        <input class="down-btn" type="image" src="{% static 'mainpage/img/down-arrow-symbol-in-black-square-button.svg' %}" value="Down">  
                    </div>              
                </div>

                <div class="accordion-content">
                    <p>> Code: Python (★★), Java (★).</p>
                    <p>> Design: Figma (★★★★), Photoshop (★★★).</p>
                    <p>> Others: Piano (★★), Photography (★).</p>
                </div>
            </div>

            

        </div>
    </div>
</div>
{% include 'mainpage/footer.html' %}
{% endblock %}

mainpage/templates/mainpage/other.html
{% extends 'mainpage/base.html' %}

{% load static %}

{% block title %}
Coming Soon
{% endblock %}



{% block content %}
{% include 'mainpage/header.html' %}
<div class="container-xl">
    <h1>Hello.</h1>
    <div class="yoy">
        <p class="long-par">This page currently under construction because the creator have no idea what to put in here. More content coming soon !<br>In the meantime, please keep in watch for this lil bean. Thanks!</p>
        <div class="bean">
            <img src="{% static 'mainpage/img/bean.png' %}">
        </div>
    </div>
</div>

{% include 'mainpage/footer.html' %}
{% endblock %}