accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

booksearch/urls.py
from django.urls import path

from . import views

app_name = 'booksearch'

urlpatterns = [
    path('', views.index, name='index'),
]

matkul/urls.py
from django.urls import path

from . import views

app_name = 'matkul'

urlpatterns = [
    path('', views.list_matkul, name='list_matkul'),
    path('create-course', views.create_matkul, name='create_matkul'),
    path('update-course/<slug:slug>', views.update_matkul, name='update_matkul'),
    path('delete-course/<slug:slug>', views.delete_matkul, name='delete_matkul'),
    path('course-details/<slug:slug>', views.matkul_desc, name='matkul_desc')

]

webtimi/urls.py
from django.contrib import admin
from django.urls import path, include
from booksearch import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('story1/', include('story1.urls')),
    path('courses/', include('matkul.urls')),
    path('activities/', include('activities.urls')),
    path('accounts/', include('accounts.urls')),
    path('book-search/', include('booksearch.urls')),
    path('book-data/', views.book_data, name='book_data'),
]

booksearch/models.py
from django.db import models

# Create your models here.

booksearch/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import requests
# Create your views here.
def index(request):
    return render(request, "booksearch/index.html")

def book_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']   # getting the API's URL corresponding to the param
    resp = requests.get(url)    # from the request we get the response, response.content is the JSON (content) we're looking for
    bookData = json.loads(resp.content)  # Here we parse the JSON string (resp.content) into python dictionaries
    return JsonResponse(bookData, safe=False)   # Return the data into JSON as a response

booksearch/templates/booksearch/index.html
{% extends 'mainpage/base.html' %}

{% load static %}


{% block js %}
<script src="{% static 'booksearch/script.js' %}"></script>
{% endblock %}



{% block content %}

{% include 'mainpage/header.html' %}
<div class="container-xl book-searching">
  <h1>Search</h1>
  {% if user.is_authenticated %}
  <p class="sub-heading">Search books here!</p>
  <input type="text" id="search-keywords" placeholder="Insert the book's title...">
  {% else %}
  <!--redirect to previous page in Django after POST request (catching the next)-->
  <p class="sub-heading">Please <a href="{% url 'accounts:login' %}?next={{ request.path|urlencode }}">login first</a> in order to use this search.</p>
  <input type="text" id="search-keywords" placeholder="Insert the book's title..." disabled>
  {% endif %}
</div>

<div class="container-xl book-search-result">
  <h1>Result</h1>
  <div class="table-responsive-xl">
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Author(s)</th>
            <th scope="col">Description</th>
            <th scope="col">Cover</th>
          </tr>
        </thead>

        <tbody class="books-info">
          <tr>
          </tr>
        </tbody>

    </table>
  </div>
</div>

{% endblock %}